Repository HSU-Likelion12-yourSide/YourSide-Front, pull requests merged in 2024-11, with the labels that each got.

#74 네편현답 상세 보기 (ViewQuestionAndAnswer) 페이지 컴포넌트 분리와 코멘트 API를 연결한다.
  src/Global/API/Hooks/useFetchAPI.jsx
  src/Page/QuestionAndAnswer/components/VQnAComment.component.jsx
  src/Page/QuestionAndAnswer/components/VQnACommentList.component.jsx
  src/Page/QuestionAndAnswer/components/ViewQuestionAndAnswer.jsx
  src/Page/QuestionAndAnswer/css/VQnAComment.scss
  src/Page/QuestionAndAnswer/css/VQnACommentList.scss
  src/Page/QuestionAndAnswer/css/ViewQuestionAndAnswer.scss
  src/Page/QuestionAndAnswer/image/badClick.svg
  src/Page/QuestionAndAnswer/image/likeClick.svg
Labels: ⚛React, 🏗API

#68 게시글 작성(PostingQnA)페이지 css 작업을 마무리한다.
  src/App.jsx
  src/DevTerminal.jsx
  src/Global/components/ModalType/ModalGetResult.components.jsx
  src/Global/components/ModalType/ModalResultList.components.jsx
  src/Global/css/ModalType/Modal.resultget.scss
  src/Global/css/ModalType/Modal.resultlist.scss
  src/Global/image/modal-closeIcon.svg
  src/Page/PostingQnA/components/PostingQnA.jsx
  src/Page/PostingQnA/css/PostingQnA.scss
  src/Page/PostingQnA/image/plusIcon.svg
  src/Page/QuestionAndAnswer/components/QuestionAndAnswer.jsx
Labels: 💅SCSS, 💄Styled

#78 공지사항(Notice) 페이지의 기능 구현과 API 통신을 한다.
  src/App.jsx
  src/DevTerminal.jsx
  src/Page/Notice/components/Notice.jsx
  src/Page/Notice/components/NoticeElement.component.jsx
  src/Page/Notice/css/Notice.scss
  src/Page/Notice/css/NoticeElement.scss
  src/Page/Notice/img/page-left-arrow.svg
  src/Page/Notice/img/page-right-arrow.svg
  src/Page/PostingQnA/components/PostingQnA.jsx
  src/Page/PostingQnA/css/PostingQnA.scss
  src/Page/PostingQnA/image/plusIcon.svg
  src/Page/QnAPosting/components/QnAPosting.jsx
  src/Page/QnAPosting/css/QnAPosting.scss
  src/Page/QuestionAndAnswer/components/QuestionAndAnswer.jsx
Labels: ⚛React, 💅SCSS, 💄Styled, 🏗API, ♻ refactoring

#80 Login, Signup 페이지를 리팩토링한다.
  src/App.jsx
  src/DevTerminal.jsx
  src/Page/Login/FindID/components/FindID.jsx
  src/Page/Login/FindID/function/undefined.js
  src/Page/Login/FindID/test/undfined.js
  src/Page/Login/FindPW/components/FindPW.jsx
  src/Page/Login/FindPW/function/undefined.js
  src/Page/Login/FindPW/test/undfined.js
  src/Page/Login/SignUp/function/undefined.js
  src/Page/Login/SignUp/test/undfined.js
  src/Page/Login/components/FindUser.jsx
  src/Page/Login/components/Findid.component.jsx
  src/Page/Login/components/Findpw.component.jsx
  src/Page/Login/components/Login.component.jsx
  src/Page/Login/components/Login.jsx
  src/Page/Login/components/Login.test.jsx
  src/Page/Login/components/SignUp.component.jsx
  src/Page/Login/components/SignUp.jsx
  src/Page/Login/components/SignUp.test.jsx
  src/Page/Login/css/FindUser.scss
  src/Page/Login/css/Findid.component.scss
  src/Page/Login/css/Findpw.component.scss
  src/Page/Login/css/Login.component.scss
  src/Page/Login/css/Login.scss
  src/Page/Login/css/SignUp.component.scss
  src/Page/Login/css/SignUp.scss
  src/Page/Login/css/login.test.css
  src/Page/Login/css/signup.test.css
  src/Page/Login/function/undefined.js
  src/Page/Login/img/symbol-logo-row.png
Labels: ⚛React, 💅SCSS, 💄Styled, 🏗API, ♻ refactoring

#84 내 근로 정리 (WorkArrangement) 페이지 컴포넌트 분리와 API를 연결한다.
  src/App.jsx
  src/Global/components/Modal.components.jsx
  src/Global/components/ModalType/ModalResult.components.jsx
  src/Global/components/ModalType/ModalResultMessage.components.jsx
  src/Global/components/ModalType/ModalShareMessage.components.jsx
  src/Global/components/VmwrResult.component.jsx
  src/Global/css/VmwrResult.component.scss
  src/Page/WorkArrangement/components/ViewMyWork.jsx
  src/Page/WorkArrangement/components/ViewMyWorkOption.component.jsx
  src/Page/WorkArrangement/components/ViewMyWorkResult.jsx
  src/Page/WorkArrangement/components/ViewMyWorkResultCalculate.jsx
  src/Page/WorkArrangement/components/WorkArrangement.jsx
  src/Page/WorkArrangement/components/WorkArrangementList.jsx
  src/Page/WorkArrangement/components/WorkArrangementResult.component.jsx
  src/Page/WorkArrangement/components/type/VmwBinaryAnswer.component.jsx
  src/Page/WorkArrangement/components/type/VmwInputAnswer.component.jsx
  src/Page/WorkArrangement/components/type/VmwMultiAnswer.component.jsx
  src/Page/WorkArrangement/css/ViewMyWork.scss
  src/Page/WorkArrangement/css/ViewMyWorkResult.scss
  src/Page/WorkArrangement/css/WorkArrangementResult.scss
  src/Page/WorkArrangement/data/viewMyWork.data.js
  src/Page/WorkArrangement/function/generateResultContent.js
Labels: ⚛React, 🏗API

#85 네편현답 상세 보기 (ViewQuestionAndAnswer) 페이지 코멘트 API GET 부분을 다시 확인한다.
  src/Page/QuestionAndAnswer/components/VQnAComment.component.jsx
  src/Page/QuestionAndAnswer/components/VQnACommentList.component.jsx
  src/Page/QuestionAndAnswer/components/ViewQuestionAndAnswer.jsx
  src/Page/QuestionAndAnswer/css/QuestionAndAnswer.css
Labels: ⚛React, 🏗API, 🐞Bug

#88 worksheetId 가 포함된 부분을 수정한다.
  src/App.jsx
  src/Global/components/ModalType/ModalGetResult.components.jsx
  src/Global/components/ModalType/ModalResult.components.jsx
  src/Global/components/ModalType/ModalResultList.components.jsx
  src/Global/components/ModalType/ModalResultMessage.components.jsx
  src/Global/components/VmwrResult.component.jsx
  src/Global/css/ModalType/Modal.result.scss
  src/Global/css/ModalType/Modal.resultget.scss
  src/Global/css/ModalType/Modal.resultlist.scss
  src/Page/QuestionAndAnswer/components/ViewQuestionAndAnswer.jsx
  src/Page/WorkArrangement/components/ViewMyWorkResult.jsx
Labels: ⚛React, ♻ refactoring

#90 네편현답 상세 보기 (ViewQuestionAndAnswer) 페이지 코멘트 영역의 프레임 드랍 현상을 해결한다.
  src/Page/QuestionAndAnswer/components/VQnAComment.component.jsx
  src/Page/QuestionAndAnswer/components/VQnACommentList.component.jsx
Labels: ⚛React, 🏗API, 🐞Bug, ♻ refactoring

#92 게시글 작성(PostingQnA)페이지 api를 연결한다.
  src/Global/ContextProviderState.jsx
  src/Global/components/ModalType/ModalGetResult.components.jsx
  src/Global/components/ModalType/ModalResultList.components.jsx
  src/Global/components/VmwrResult.component.jsx
  src/Global/css/ModalType/Modal.resultlist.scss
  src/Page/QnAPosting/components/QnAPosting.jsx
  src/Page/QuestionAndAnswer/components/QuestionAndAnswer.jsx
Labels: ⚛React, 🏗API, 🐞Bug

#95 네편현답 상세 보기 (ViewQuestionAndAnswer) 페이지 css 문제 부분을 수정한다. #91
  src/Page/Main/components/Main.jsx
  src/Page/Main/css/Main.scss
  src/Page/MyPage/components/MyPage.Result.component.jsx
  src/Page/MyPage/components/MyPage.ResultElement.jsx
  src/Page/MyPage/components/MyPage.ViewResult.jsx
  src/Page/MyPage/css/MyPage.Result.scss
  src/Page/MyPage/function/resultWorkTitle.js
  src/Page/MyPage/function/undefined.js
  src/Page/QuestionAndAnswer/css/Question.scss
  src/Page/QuestionAndAnswer/css/QuestionAndAnswer.scss
  src/Page/QuestionAndAnswer/css/VQnACommentList.scss
  src/Page/QuestionAndAnswer/css/ViewQuestionAndAnswer.scss
Labels: ⚛React, ♻ refactoring

#96 전체 페이지를 검사한다.
  src/App.jsx
  src/Global/ContextProviderState.jsx
  src/Global/components/ModalType/ModalShareMessage.components.jsx
  src/Page/Footer/css/Footer.scss
  src/Page/Header/components/Header.jsx
  src/Page/Login/components/Login.component.jsx
  src/Page/Main/components/Main.jsx
  src/Page/MyPage/components/MyPage.ResultElement.jsx
  src/Page/MyPage/components/MyPage.ViewResult.jsx
  src/Page/MyPage/components/MyPage.jsx
  src/Page/QuestionAndAnswer/components/Question.component.jsx
  src/Page/QuestionAndAnswer/components/QuestionAndAnswer.jsx
  src/Page/QuestionAndAnswer/components/RankQuestion.component.jsx
  src/Page/QuestionAndAnswer/components/VQnAComment.component.jsx
  src/Page/QuestionAndAnswer/components/VQnACommentList.component.jsx
  src/Page/QuestionAndAnswer/components/ViewQuestionAndAnswer.jsx
  src/Page/WorkArrangement/components/ViewMyWork.jsx
  src/Page/WorkArrangement/components/ViewMyWorkOption.component.jsx
  src/Page/WorkArrangement/components/ViewMyWorkResult.jsx
  src/Page/WorkArrangement/components/ViewMyWorkResultCalculate.jsx
  src/Page/WorkArrangement/components/WorkArrangement.jsx
  src/Page/WorkArrangement/components/WorkArrangementResult.component.jsx
  src/Page/WorkArrangement/data/viewMyWork.data.js
  src/Page/WorkArrangement/function/generateResultContent.js
Labels: ⚛React, ♻ refactoring

#103 ContextAPI를 js-doc으로 관리한다.
  docs/global.html
  docs/index.html
  jsdoc.config.json
  src/Global/API/Hooks/useFetchAPI.jsx
  src/Global/API/fetch.instance.js
  src/Global/ContextProviderState.jsx
  src/Global/Hooks/useGlobalState.jsx
Labels: 📝Doc
